FROM php:8.2-apache
 
WORKDIR /var/www/html
 
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpq-dev \
    libzip-dev \
    zip \
&& docker-php-ext-install pdo pdo_pgsql zip \
&& a2enmod rewrite
 
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
 
COPY . .
 
RUN composer install --no-dev --optimize-autoloader
 
RUN chown -R www-data:www-data storage bootstrap/cache
 
RUN printf '<VirtualHost *:80>\n\
    DocumentRoot /var/www/html/public\n\
<Directory /var/www/html/public>\n\
        AllowOverride All\n\
        Require all granted\n\
</Directory>\n\
</VirtualHost>\n' > /etc/apache2/sites-available/000-default.conf
 
EXPOSE 80
 
CMD ["apache2-foreground"]